eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8082

spring:
  application:
    name: service-ribbon
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
